title: "Mingke Erin Li"
author: "Mingke Erin Li"
description: "We are fancy, just because we can."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true
show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "About me"}
  - {file: "blog.md", title: "Blog"}
  - {file: "research.md", title: "Research"}
  - {file: "gallery.md", title: "Gallery"}
 # - {file: "cv.html", title: "CV"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mingke.li@ucalgary.ca"}
  - {title: GitHub, icon: github, url: "https://github.com/Erin-1919"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Mingke-Li"}
  - {title: LinkedIn, icon: linkedin, url: "www.linkedin.com/in/mingke-erin-li"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jemoji
 - jekyll-seo-tag
