title: "Mingke Erin Li"
author: "Mingke Erin Li"
description: "Bring Your Own Bottle & Do Your Own Research."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true
show_excerpts: false
show_frame: true
show_sidebar: false
minimal: true

# Menu

navigation:
  - {file: "index.html", title: "About me"}
  - {file: "blog.md", title: "Blog"}
  - {file: "research.md", title: "Research"}
  - {file: "gallery.md", title: "Gallery"}
 # - {file: "cv.html", title: "CV"}
  
external:
  - {title: Mail, icon: envelope, url: "mailto:mingke.li@ucalgary.ca"}
  - {title: GitHub, icon: github, url: "https://github.com/Erin-1919"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Mingke-Li"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/mingke-erin-li"}

comments:
#  disqus_shortname: ""
#  isso_domain: ""

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"