title: "Mingke Erin Li"
author: "Mingke Erin Li"
description: "Bring Your Own Bottle & Do Your Own Research."
lang: "en"
baseurl: ""
url: "https://Erin-1919.github.io"
permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-email-protect
  - jekyll-redirect-from
  - jekyll-paginate

collections:
  publications:
    output: false
  news:
    output: true
    permalink: /news/:path/
  showcase:
    output: false
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog_post"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - docs/
  - CLAUDE.md
  - UNLICENSE.txt
